package nonmod

import (
	"github.com/bcmills/uuid61/v4/nonmod"
)

// generated by goforward --filename=nonmod.go --replace github.com/bcmills/uuid61/v4/nonmod github.com/bcmills/uuid61/nonmod

func PrintUUID() {
	nonmod.PrintUUID()
}
